version: "3.8"

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"   # Interface Web Nexus
      - "5000:5000"   # Docker Registry (si activé)
    volumes:
      - nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx1024m
    restart: unless-stopped
    networks:
      - nexus-net

volumes:
  nexus-data:

networks:
  nexus-net:
