name: CI - Build and Analyze

on:
  push:
    branches: [ "gestion-materiel" ]
  pull_request:
    branches: [ "gestion-materiel" ]

jobs:
  build:
    name: Build & SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🧪 Run Tests
        run: mvn test

      - name: 📦 Build (skip tests)
        run: mvn package -DskipTests

      - name: 🔍 SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify sonar:sonar \
          -Dsonar.projectKey=Microservice-Springboot-Angular \
          -Dsonar.organization=dawdi01 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
